import type { INodeProperties } from 'n8n-workflow';

export const orderFiltersProperty: INodeProperties = {
	displayName: 'Additional Filters',
	name: 'additionalFilters',
	type: 'collection',
	placeholder: 'Add Filter',
	default: {},
	displayOptions: {
		show: {
			resource: ['order'],
			operation: ['getMany'],
		},
	},
	options: [
		{
			displayName: 'Customer Email',
			name: 'customerEmail',
			type: 'string',
			default: '',
			description: 'Filter by customer email',
		},
		{
			displayName: 'Customer ID',
			name: 'customerId',
			type: 'string',
			default: '',
			description: 'Filter by customer ID',
		},
		{
			displayName: 'Order Number',
			name: 'orderNumber',
			type: 'string',
			default: '',
			description: 'Filter by order number',
		},
		{
			displayName: 'Order Status',
			name: 'status',
			type: 'multiOptions',
			default: [],
			description: 'Filter orders by status',
			options: [
				{ name: 'Cancelled', value: 'CANCELLED' },
				{ name: 'Confirmed', value: 'CONFIRMED' },
				{ name: 'Created', value: 'CREATED' },
				{ name: 'Fulfilled', value: 'FULFILLED' },
				{ name: 'Partially Fulfilled', value: 'PARTIALLY_FULFILLED' },
				{ name: 'Refunded', value: 'REFUNDED' },
			],
		},
		{
			displayName: 'Order Package Status',
			name: 'orderPackageStatus',
			type: 'multiOptions',
			default: [],
			description: 'Filter orders by package status',
			options: [
				{ name: 'Cancelled', value: 'CANCELLED' },
				{ name: 'Cancel Rejected', value: 'CANCEL_REJECTED' },
				{ name: 'Cancel Requested', value: 'CANCEL_REQUESTED' },
				{ name: 'Delivered', value: 'DELIVERED' },
				{ name: 'Fulfilled', value: 'FULFILLED' },
				{ name: 'Partially Cancelled', value: 'PARTIALLY_CANCELLED' },
				{ name: 'Partially Delivered', value: 'PARTIALLY_DELIVERED' },
				{ name: 'Partially Fulfilled', value: 'PARTIALLY_FULFILLED' },
				{ name: 'Partially Ready for Shipment', value: 'PARTIALLY_READY_FOR_SHIPMENT' },
				{ name: 'Partially Refunded', value: 'PARTIALLY_REFUNDED' },
				{ name: 'Ready for Pick Up', value: 'READY_FOR_PICK_UP' },
				{ name: 'Ready for Shipment', value: 'READY_FOR_SHIPMENT' },
				{ name: 'Refunded', value: 'REFUNDED' },
				{ name: 'Refund Rejected', value: 'REFUND_REJECTED' },
				{ name: 'Refund Requested', value: 'REFUND_REQUESTED' },
				{ name: 'Refund Request Accepted', value: 'REFUND_REQUEST_ACCEPTED' },
				{ name: 'Unable to Deliver', value: 'UNABLE_TO_DELIVER' },
				{ name: 'Unfulfilled', value: 'UNFULFILLED' },
			],
		},
		{
			displayName: 'Order Payment Status',
			name: 'orderPaymentStatus',
			type: 'multiOptions',
			default: [],
			description: 'Filter orders by payment status',
			options: [
				{ name: 'Failed', value: 'FAILED' },
				{ name: 'Paid', value: 'PAID' },
				{ name: 'Partially Paid', value: 'PARTIALLY_PAID' },
				{ name: 'Waiting', value: 'WAITING' },
			],
		},
	],
};
